# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-04 16:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fakesketchfab', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model3d',
            name='about',
            field=models.OneToOneField(blank=True, null=django.db.models.deletion.SET_NULL, on_delete=django.db.models.deletion.CASCADE, related_name='model_3d', to='fakesketchfab.ModelDescription'),
        ),
    ]
